// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package myapp

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetAllUsersRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetAllUsersRequest(buf []byte, offset flatbuffers.UOffsetT) *GetAllUsersRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetAllUsersRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetAllUsersRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetAllUsersRequest(buf []byte, offset flatbuffers.UOffsetT) *GetAllUsersRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetAllUsersRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetAllUsersRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetAllUsersRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetAllUsersRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func GetAllUsersRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func GetAllUsersRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
