// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package myapp

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsUserRequest(buf []byte, offset flatbuffers.UOffsetT) *UserRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishUserRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsUserRequest(buf []byte, offset flatbuffers.UOffsetT) *UserRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UserRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedUserRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *UserRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserRequest) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UserRequest) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func UserRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func UserRequestAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func UserRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
